baseURL = "https://tunagrskn.github.io/tg-blog/"
theme = "blowfish"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
summaryLength = 30

[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 1
    
  [languages.tr]
    languageCode = "tr"
    languageName = "Türkçe"
    weight = 2

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  changefreq = "weekly"
  priority = 0.5