baseURL = "https://tunagirisken.com/"
theme = "blowfish"

defaultContentLanguage = "tr"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
summaryLength = 30

[languages]
  [languages.tr]
    languageCode = "tr"
    languageName = "Türkçe"
    weight = 1

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true