baseURL = "https://tunagrskn.github.io/tg-blog/"
theme = "blowfish"
defaultContentLanguage = "tr"

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
